# Generated by Django 4.2.1 on 2023-06-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation', models.IntegerField(choices=[(1, 'Antalya'), (2, 'Izmir'), (3, 'Istanbul'), (4, 'Fethiye'), (5, 'Bodrum'), (6, 'Datça'), (7, 'Urla')])),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('visitor_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
