# Generated by Django 4.2 on 2023-06-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rezervation_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RezervationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('user_age', models.CharField(choices=[('ucretsiz', '0-12'), ('tam', '12-65'), ('%50 indirimli', '65+')], max_length=16, null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('-', 'Prefer not to say')], max_length=1, null=True)),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel.rezervation')),
            ],
        ),
    ]
