# Generated by Django 4.2 on 2023-06-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rezervationdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervationdetail',
            name='user_age',
            field=models.CharField(choices=[('ucretsiz', '0-12'), ('tam bilet', '12-65'), ('%50 indirimli', '65+')], max_length=16, null=True),
        ),
    ]
