# Generated by Django 4.2.1 on 2023-06-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
