# Generated by Django 4.2 on 2023-06-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customer_number_customer_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_age',
            field=models.CharField(choices=[('ucretsiz', '0-12'), ('tam', '12-65'), ('%50 indirimli', '65+')], max_length=16, null=True),
        ),
    ]
